# Generated by Django 3.0.5 on 2020-04-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_profile_born'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='name',
        ),
    ]
